import 'dart:async';

import '../models/device.dart';
import 'compliance_service.dart';
import 'config_service.dart';
import 'device_service.dart';
import 'manual_search_service.dart';

/// 登録完了後に公式マニュアルURLのみを非同期解決（PDF保存なし）
class ManualLinkResolver {
  ManualLinkResolver._();
  static final ManualLinkResolver instance = ManualLinkResolver._();

  final ManualSearchService _manualSearch =
      ManualSearchService(ConfigService());
  final Map<String, Future<String?>> _inFlight = {};

  String _dedupeKey(String manufacturer, String modelNumber) =>
      '${manufacturer.trim().toLowerCase()}|${modelNumber.trim().toLowerCase()}';

  /// 型番確定前のキャッシュ温め（登録ボタン押下前に呼べる）
  Future<void> prefetch(String manufacturer, String modelNumber) async {
    if (manufacturer.trim().isEmpty && modelNumber.trim().isEmpty) return;
    final key = _dedupeKey(manufacturer, modelNumber);
    _inFlight.putIfAbsent(
      key,
      () => _resolveUrl(manufacturer, modelNumber),
    );
    await _inFlight[key];
  }

  /// デバイス登録後にバックグラウンドで公式リンクを解決
  void resolveForDevice(DeviceService deviceService, Device device) {
    if (device.manufacturer.trim().isEmpty &&
        device.modelNumber.trim().isEmpty) {
      return;
    }
    unawaited(_resolveAndUpdate(deviceService, device));
  }

  Future<void> _resolveAndUpdate(
    DeviceService deviceService,
    Device device,
  ) async {
    await deviceService.updateDeviceManualState(
      device.id,
      ManualFetchState.fetching,
    );

    try {
      final url = await _resolveUrl(device.manufacturer, device.modelNumber);
      if (url == null || url.isEmpty) {
        await deviceService.updateDeviceManualState(
          device.id,
          ManualFetchState.notFound,
        );
        return;
      }

      final manual = Manual(
        url: url,
        autoGenerated: true,
        lastUpdated: DateTime.now().toIso8601String(),
        source: 'official',
      );
      await deviceService.updateDeviceManual(device.id, manual);
    } catch (e) {
      await ComplianceService.logEvent(
        action: 'manual_link_resolve_error',
        targetId: device.id,
        result: 'error',
        reason: e.toString(),
      );
      await deviceService.updateDeviceManualState(
        device.id,
        ManualFetchState.notFound,
      );
    }
  }

  Future<String?> _resolveUrl(String manufacturer, String modelNumber) async {
    final key = _dedupeKey(manufacturer, modelNumber);
    if (_inFlight.containsKey(key)) {
      return _inFlight[key];
    }

    final future = _resolveUrlImpl(manufacturer, modelNumber);
    _inFlight[key] = future;
    try {
      return await future;
    } finally {
      _inFlight.remove(key);
    }
  }

  Future<String?> _resolveUrlImpl(
    String manufacturer,
    String modelNumber,
  ) async {
    final cached =
        await _manualSearch.getCachedUrl(manufacturer, modelNumber);
    if (cached != null && cached.isNotEmpty) {
      return cached;
    }
    return _manualSearch.searchManualUrl(manufacturer, modelNumber);
  }
}
