import 'package:flutter_test/flutter_test.dart';
import 'package:homtune/models/device.dart';
import 'package:homtune/services/device_service.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  setUp(() {
    SharedPreferences.setMockInitialValues({});
  });

  group('DeviceService.loadData', () {
    test('keeps user-added devices across reload', () async {
      final service = DeviceService();

      final userDevice = Device(
        id: 'user-custom-001',
        name: 'Custom Fan',
        modelNumber: 'CF-1',
        category: 'Fan',
        manufacturer: 'UserCo',
        purchaseDate: '2025-01-01',
        purchasePrice: 12000,
        yearsOwned: 0.5,
        room: 'living-room',
        location: 'floor',
        status: 'active',
        consumables: [],
        photos: [],
        documents: [],
      );

      await service.addDevice(userDevice);
      expect(service.devices.any((d) => d.id == 'user-custom-001'), isTrue);

      await service.loadData();
      while (service.isLoading) {
        await Future.delayed(const Duration(milliseconds: 50));
      }

      expect(service.devices.any((d) => d.id == 'user-custom-001'), isTrue);
    });

    test('isLoading is false only after load completes', () async {
      final service = DeviceService();
      final loadFuture = service.loadData();

      var sawLoading = false;
      for (var i = 0; i < 50; i++) {
        if (service.isLoading) sawLoading = true;
        await Future.delayed(const Duration(milliseconds: 20));
      }

      await loadFuture;
      expect(sawLoading, isTrue);
      expect(service.isLoading, isFalse);
    });
  });

  group('DeviceService persistence', () {
    test('consumePendingUserMessage returns one-shot notification', () async {
      final service = DeviceService();
      expect(service.consumePendingUserMessage(), isNull);

      final device = Device(
        id: 'user-msg-001',
        name: 'Test',
        modelNumber: 'T',
        category: 'TV',
        manufacturer: 'M',
        purchaseDate: '2025-01-01',
        purchasePrice: 1000,
        yearsOwned: 0,
        room: 'living-room',
        location: 'x',
        status: 'active',
        consumables: [],
        photos: [],
        documents: [],
      );
      await service.addDevice(device);
      await service.updateDeviceManual(
        'user-msg-001',
        Manual(
          url: 'https://example.com/manual.pdf',
          autoGenerated: true,
          lastUpdated: DateTime.now().toIso8601String(),
          source: 'official',
        ),
      );

      expect(service.consumePendingUserMessage(), isNotNull);
      expect(service.consumePendingUserMessage(), isNull);
    });
  });
}
