class Manual {
  /// URLまたはローカルファイルパス
  /// - 外部URL: `https://example.com/manual.pdf`
  /// - ローカルファイル: `file:///path/to/manual.pdf`
  final String url;
  final bool autoGenerated;
  final String lastUpdated;

  /// マニュアルのソース: 'official' (公式サイト), 'scanned' (スキャン生成), 'uploaded' (アップロード)
  final String source;

  Manual({
    required this.url,
    required this.autoGenerated,
    required this.lastUpdated,
    this.source = 'official',
  });

  factory Manual.fromJson(Map<String, dynamic> json) {
    try {
      return Manual(
        url: json['url']?.toString() ?? '',
        autoGenerated: json['autoGenerated'] == true,
        lastUpdated: json['lastUpdated']?.toString() ?? '',
        source: json['source']?.toString() ?? 'official',
      );
    } catch (e) {
      print('Error parsing Manual: $e');
      return Manual(
        url: '',
        autoGenerated: false,
        lastUpdated: '',
        source: 'official',
      );
    }
  }

  Map<String, dynamic> toJson() {
    return {
      'url': url,
      'autoGenerated': autoGenerated,
      'lastUpdated': lastUpdated,
      'source': source,
    };
  }

  /// ローカルファイルかどうかを判定
  bool get isLocalFile => url.startsWith('file://');

  /// 外部URLかどうかを判定
  bool get isExternalUrl => !isLocalFile && url.isNotEmpty;
}
